### PR TITLE
Refactor Snowflake role to remove duplication, and update for ansible-core

### PR DESCRIPTION
**Pull request by jbjorkang**
I stumbled across this role by reading about Snowflake, and felt like I could help out to make managing it a bit easier.

What I have done here is:
- Removed the separate distribution task files in favour of ones that cover all distributions
- Used dynamic variable includes to select the correct package names across distributions
- Used the FQCNs that are now in use by ansible-core
- Added a handler for when the configuration has changed, or the binary has been rebuilt
- Slimmed down some tasks and added some helper defaults

I have only been fully able to test this on Fedora 36, but since it is only the logic that has been refactored, rather than the content I would like to hope it is alright across other distributions!

Hope I didn't step on any toes with this, I got a bit carried away!

### CODE REVIEW

**Comment by nvjacobo** [comment]
Hi @jbjorkang 

Thank you for your kind contributions.

Some comments from my side:


Arch

```
TASK [snowflake : Install ['golang']] ****************************************************************************************************************
fatal: []: FAILED! => {"changed": false, "msg": "Could not import the dnf python module using /usr/bin/python (3.10.4 (main, Mar 23 2022, 23:05:40) [GCC 11.2.0]). Please install `python3-dnf` or `python2-dnf` package or ensure you have specified the correct ansible_python_interpreter. (attempted ['/usr/libexec/platform-python', '/usr/bin/python3', '/usr/bin/python2', '/usr/bin/python'])", "results": []}

```



Debian Buster

```
TASK [snowflake : Install ['golang']] ****************************************************************************************************************
fatal: []: FAILED! => {"changed": false, "msg": "Unsupported parameters for (ansible.builtin.dnf) module: default_release. Supported parameters include: lock_timeout, disable_gpg_check, conf_file, exclude, allow_downgrade, allowerasing, nobest, disable_excludes, validate_certs, state, disablerepo, releasever, skip_broken, autoremove, download_dir, name (pkg), installroot, install_weak_deps, update_cache (expire-cache), download_only, bugfix, list, install_repoquery, update_only, disable_plugin, enablerepo, security, enable_plugin."}
```

Debian Bullseye

```
TASK [snowflake : Install ['golang']] ****************************************************************************************************************
fatal: []: FAILED! => {"changed": false, "msg": "Could not import the dnf python module using /usr/bin/python3 (3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110]). Please install `python3-dnf` or `python2-dnf` package or ensure you have specified the correct ansible_python_interpreter. (attempted ['/usr/libexec/platform-python', '/usr/bin/python3', '/usr/bin/python2', '/usr/bin/python'])", "results": []}
```

Ubuntu 

```
TASK [snowflake : Install ['golang']] ****************************************************************************************************************
fatal: []: FAILED! => {"changed": false, "msg": "Could not import the dnf python module using /usr/bin/python3 (3.10.4 (main, Apr  2 2022, 09:04:19) [GCC 11.2.0]). Please install `python3-dnf` or `python2-dnf` package or ensure you have specified the correct ansible_python_interpreter. (attempted ['/usr/libexec/platform-python', '/usr/bin/python3', '/usr/bin/python2', '/usr/bin/python'])", "results": []}
```

Fedora (36)

TASK [snowflake : Download and build Go dependencies (get & build)] **********************************************************************************
failed: [] (item=get) => {"ansible_loop_var": "item", "changed": false, "item": "get", "msg": "Unable to change directory before execution: [Errno 2] No such file or directory: b'/home/snowflake/repo/proxy'"}
failed: [] (item=build) => {"ansible_loop_var": "item", "changed": false, "item": "build", "msg": "Unable to change directory before execution: [Errno 2] No such file or directory: b'/home/snowflake/repo/proxy'"}


FreeBSD

```
TASK [snowflake : Include OS specific variables] *****************************************************************************************************
skipping: []

TASK [snowflake : Add snowflake user] ****************************************************************************************************************
skipping: []

TASK [snowflake : Add backports for Debian Buster repository] ****************************************************************************************
skipping: []

TASK [snowflake : Install ['golang']] ****************************************************************************************************************
skipping: []

TASK [snowflake : Ensure Git is installed] ***********************************************************************************************************
skipping: []

TASK [snowflake : Ensure /home/snowflake/repo exists] ************************************************************************************************
skipping: []

TASK [snowflake : Clone snowflake repo] **************************************************************************************************************
skipping: []

TASK [snowflake : Download and build Go dependencies (get & build)] **********************************************************************************
skipping: [] => (item=get) 
skipping: [] => (item=build) 

TASK [snowflake : Copy binary file to /usr/bin/] *****************************************************************************************************
skipping: []

TASK [snowflake : Add Snowflake systemd unit] ********************************************************************************************************
skipping: []

TASK [snowflake : Run systemd daemon_reload] *********************************************************************************************************
skipping: []

TASK [snowflake : Enable snowflake-proxy service] ****************************************************************************************************
skipping: []

TASK [snowflake : Config pkg repo] *******************************************************************************************************************
skipping: []

TASK [snowflake : Install package snowflake-tor] *****************************************************************************************************
skipping: []

TASK [snowflake : Enable snowflake on boot] **********************************************************************************************************
skipping: []

TASK [snowflake : Start service snowflake] ***********************************************************************************************************
skipping: []

PLAY RECAP *******************************************************************************************************************************************
           : ok=1    changed=0    unreachable=0    failed=0    skipped=16   rescued=0    ignored=0   
```

**Comment by jbjorkang** [comment]
> Hi @jbjorkang 
> 
> Thank you for your kind contributions.
> 
> Some comments from my side:
> 
> 
> Arch
> 
> ```
> TASK [snowflake : Install ['golang']] ****************************************************************************************************************
> fatal: []: FAILED! => {"changed": false, "msg": "Could not import the dnf python module using /usr/bin/python (3.10.4 (main, Mar 23 2022, 23:05:40) [GCC 11.2.0]). Please install `python3-dnf` or `python2-dnf` package or ensure you have specified the correct ansible_python_interpreter. (attempted ['/usr/libexec/platform-python', '/usr/bin/python3', '/usr/bin/python2', '/usr/bin/python'])", "results": []}
> 
> ```
> 
> 
> 
> Debian Buster
> 
> ```
> TASK [snowflake : Install ['golang']] ****************************************************************************************************************
> fatal: []: FAILED! => {"changed": false, "msg": "Unsupported parameters for (ansible.builtin.dnf) module: default_release. Supported parameters include: lock_timeout, disable_gpg_check, conf_file, exclude, allow_downgrade, allowerasing, nobest, disable_excludes, validate_certs, state, disablerepo, releasever, skip_broken, autoremove, download_dir, name (pkg), installroot, install_weak_deps, update_cache (expire-cache), download_only, bugfix, list, install_repoquery, update_only, disable_plugin, enablerepo, security, enable_plugin."}
> ```
> 
> Debian Bullseye
> 
> ```
> TASK [snowflake : Install ['golang']] ****************************************************************************************************************
> fatal: []: FAILED! => {"changed": false, "msg": "Could not import the dnf python module using /usr/bin/python3 (3.9.2 (default, Feb 28 2021, 17:03:44) [GCC 10.2.1 20210110]). Please install `python3-dnf` or `python2-dnf` package or ensure you have specified the correct ansible_python_interpreter. (attempted ['/usr/libexec/platform-python', '/usr/bin/python3', '/usr/bin/python2', '/usr/bin/python'])", "results": []}
> ```
> 
> Ubuntu 
> 
> ```
> TASK [snowflake : Install ['golang']] ****************************************************************************************************************
> fatal: []: FAILED! => {"changed": false, "msg": "Could not import the dnf python module using /usr/bin/python3 (3.10.4 (main, Apr  2 2022, 09:04:19) [GCC 11.2.0]). Please install `python3-dnf` or `python2-dnf` package or ensure you have specified the correct ansible_python_interpreter. (attempted ['/usr/libexec/platform-python', '/usr/bin/python3', '/usr/bin/python2', '/usr/bin/python'])", "results": []}
> ```
> 
> Fedora (36)
> 
> TASK [snowflake : Download and build Go dependencies (get & build)] **********************************************************************************
> failed: [] (item=get) => {"ansible_loop_var": "item", "changed": false, "item": "get", "msg": "Unable to change directory before execution: [Errno 2] No such file or directory: b'/home/snowflake/repo/proxy'"}
> failed: [] (item=build) => {"ansible_loop_var": "item", "changed": false, "item": "build", "msg": "Unable to change directory before execution: [Errno 2] No such file or directory: b'/home/snowflake/repo/proxy'"}
> 
> 
> FreeBSD
> 
> ```
> TASK [snowflake : Include OS specific variables] *****************************************************************************************************
> skipping: []
> 
> TASK [snowflake : Add snowflake user] ****************************************************************************************************************
> skipping: []
> 
> TASK [snowflake : Add backports for Debian Buster repository] ****************************************************************************************
> skipping: []
> 
> TASK [snowflake : Install ['golang']] ****************************************************************************************************************
> skipping: []
> 
> TASK [snowflake : Ensure Git is installed] ***********************************************************************************************************
> skipping: []
> 
> TASK [snowflake : Ensure /home/snowflake/repo exists] ************************************************************************************************
> skipping: []
> 
> TASK [snowflake : Clone snowflake repo] **************************************************************************************************************
> skipping: []
> 
> TASK [snowflake : Download and build Go dependencies (get & build)] **********************************************************************************
> skipping: [] => (item=get) 
> skipping: [] => (item=build) 
> 
> TASK [snowflake : Copy binary file to /usr/bin/] *****************************************************************************************************
> skipping: []
> 
> TASK [snowflake : Add Snowflake systemd unit] ********************************************************************************************************
> skipping: []
> 
> TASK [snowflake : Run systemd daemon_reload] *********************************************************************************************************
> skipping: []
> 
> TASK [snowflake : Enable snowflake-proxy service] ****************************************************************************************************
> skipping: []
> 
> TASK [snowflake : Config pkg repo] *******************************************************************************************************************
> skipping: []
> 
> TASK [snowflake : Install package snowflake-tor] *****************************************************************************************************
> skipping: []
> 
> TASK [snowflake : Enable snowflake on boot] **********************************************************************************************************
> skipping: []
> 
> TASK [snowflake : Start service snowflake] ***********************************************************************************************************
> skipping: []
> 
> PLAY RECAP *******************************************************************************************************************************************
>            : ok=1    changed=0    unreachable=0    failed=0    skipped=16   rescued=0    ignored=0   
> ```
> 
> 
> 
> 
> 
> 
> 

Fixed up the typos. I had used the DNF module locally instead of the generic package module.

For FreeBSD, does it test the exact version of "13.0-RELEASE"? I mean is that what you have as a test machine? Strange that it skips if so.

**Comment by nvjacobo** [comment]
Thanks, 

All distros

```
[WARNING]: While constructing a mapping from /home/jacobo/snow-refact/roles/snowflake/tasks/build.yml, line 10, column 3, found a duplicate dict key
(register). Using last defined value only.
```

**Arch**

```
TASK [snowflake : Install ['golang']] ****************************************************************************************************************
fatal: [216.238.80.124]: FAILED! => {"changed": false, "msg": "failed to install golang: error: target not found: golang\n", "stderr": "error: target not found: golang\n", "stderr_lines": ["error: target not found: golang"], "stdout": "", "stdout_lines": []}
```

**Debian Buster**


```
TASK [snowflake : Clone snowflake repo] **************************************************************************************************************
[WARNING]: Module remote_tmp /home/snowflake/.ansible/tmp did not exist and was created with a mode of 0700, this may cause issues when running as
another user. To avoid this, create the remote_tmp dir with the correct permissions manually
```

Debian Bullseye

```
TASK [snowflake : Clone snowflake repo] **************************************************************************************************************
[WARNING]: Module remote_tmp /home/snowflake/.ansible/tmp did not exist and was created with a mode of 0700, this may cause issues when running as
another user. To avoid this, create the remote_tmp dir with the correct permissions manually
```

**FreeBSD 13.0 and 12.2**

```
TASK [snowflake : Include OS specific variables] *****************************************************************************************************
skipping: []

TASK [snowflake : Add snowflake user] ****************************************************************************************************************
skipping: []

TASK [snowflake : Add backports for Debian Buster repository] ****************************************************************************************
skipping: []

TASK [snowflake : Install ['golang']] ****************************************************************************************************************
skipping: []

TASK [snowflake : Ensure Git is installed] ***********************************************************************************************************
skipping: []

TASK [snowflake : Ensure /home/snowflake/repo exists] ************************************************************************************************
skipping: []

TASK [snowflake : Clone snowflake repo] **************************************************************************************************************
skipping: []

TASK [snowflake : Download and build Go dependencies (get & build)] **********************************************************************************
skipping: [] => (item=get) 
skipping: [] => (item=build) 

TASK [snowflake : Copy binary file to /usr/bin/] *****************************************************************************************************
skipping: []

TASK [snowflake : Add Snowflake systemd unit] ********************************************************************************************************
skipping: []

TASK [snowflake : Run systemd daemon_reload] *********************************************************************************************************
skipping: []

TASK [snowflake : Enable snowflake-proxy service] ****************************************************************************************************
skipping: []

TASK [snowflake : Config pkg repo] *******************************************************************************************************************
skipping: []

TASK [snowflake : Install package snowflake-tor] *****************************************************************************************************
skipping: []

TASK [snowflake : Enable snowflake on boot] **********************************************************************************************************
skipping: []

TASK [snowflake : Start service snowflake] ***********************************************************************************************************
skipping: []

PLAY RECAP *******************************************************************************************************************************************
             : ok=1    changed=0    unreachable=0    failed=0    skipped=16   rescued=0    ignored=0  
```

**Comment by jbjorkang** [comment]
Which version of Ansible do you test with?

**Comment by nvjacobo** [comment]
Ansible Version: 5.8.0

**FreeBSD 13.0**

```
TASK [snowflake : Install package snowflake-tor] *****************************************************************************************************
fatal: []: FAILED! => {"changed": false, "msg": "failed to install snowflake-tor", "stderr": "pkg: Repository FreeBSD has a wrong packagesite, need to re-create database\npkg: Repository FreeBSD cannot be opened. 'pkg update' required\npkg: No packages available to install matching 'snowflake-tor' have been found in the repositories\n", "stderr_lines": ["pkg: Repository FreeBSD has a wrong packagesite, need to re-create database", "pkg: Repository FreeBSD cannot be opened. 'pkg update' required", "pkg: No packages available to install matching 'snowflake-tor' have been found in the repositories"], "stdout": "", "stdout_lines": []}
```

**Comment by nvjacobo** [comment]
Sorry I could not follow up. I tried to understand each of the proposed changes and follow up but my technical understanding and time did not allow me to do so. I think there are several changes you propose that should be included. But it was difficult for me to understand and assimilate all the changes, especially to keep in the future. 

I appreciate your expertise and time. Now what I plan to do is to slowly include your changes as I understand them. I am very sorry for your
 
Thanks, Jacobo

**Comment by jbjorkang** [comment]
> 

The majority of what I have done is just to consolidate the different OS versions. You do not need to have separate task files for each OS. You can combine them into one, and pass different variables to each.

I will reopen this for now. Let me know if something else is unclear.

**Pull request closed without merging**
